env:
  node: false
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  tsconfigRootDir: ./
  ecmaVersion: "latest"
  sourceType: "module"
root: true
ignorePatterns: [".eslintrc.yaml"]
plugins:
  - "@typescript-eslint"
  - "import"
  - "unused-imports"
settings:
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
rules:
  import/order:
    - "error"
    - groups:
        - "builtin"
        - "external"
        - "internal"
        - "parent"
        - "sibling"
        - "index"
      newlines-between: "always"
      alphabetize:
        order: "asc"
        caseInsensitive: true
  "unused-imports/no-unused-imports-ts": "warn"
